<?php

/* FARE Drupal Module
 *  Copyright (C) 2018 libremente (surf@libremente.eu)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 *  See LICENSE.md for extended license info.
 */

/**
 * @file
 * Documentation for the whole python.module file.
 *
 * In this file there are the following functions:
 * - setting permissions
 * - handling the preprossessing
 * - add the menu/page entry.
 */

/**
 * Set permissions.
 *
 * Implements hook_permission().
 */
function fare_python_permission() {
  $perms = array(
    'administer fare_python' => array(
      'title' => 'Amministra fare Python',
      'description' => 'Assumi il controllo totale sul modulo',
    ),
    'access fare_python' => array(
      'title' => 'Accesso alle componenti del modulo',
      'description' => 'Accesso a tutte le funzionalità del modulo',
    ),
  );
  return $perms;
}

/**
 * Pass parameters to template.
 *
 * Implements preprocess_page().
 */
function fare_python_preprocess_page(&$variables) {
  // Get parameter from variables.
  if (!empty($variables)) {
    $python_code = variable_get('python_code');
    variable_set('python_code', "");
    if (empty($python_code)) {
      $python_code = "# Inserisci qui il tuo codice";
    }
    // Setting variables for rendering.
    $variables['python_code'] = $python_code;
  }
}

/**
 * Implements hook_menu().
 */
function fare_python_menu() {
  $items = array();

  $items['python'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Esegui il tuo codice Python',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_python_page'),
    'access callback' => 'user_access',
    'access arguments' => array('access fare_python'),
  );

  return $items;
}

/**
 * Function returning null.
 */
function _python_page($page = NULL) {
  return;
}
